import plugin from '@vitest/eslint-plugin'

export default () => [
  {
    name: 'dr-mike:vitest',

    files: ['**/*.test.ts', '**/*.spec.ts'],
    languageOptions: {
      globals: { ...plugin.environments.env.globals },
    },
    plugins: { vitest: plugin },
    rules: {
      'vitest/consistent-test-filename': ['error', { pattern: String.raw`.*\.test\.ts$` }],
      'vitest/consistent-test-it': ['error', { fn: 'test', withinDescribe: 'it' }],
      'vitest/expect-expect': 'error',
      'vitest/max-expects': ['error', { max: 10 }],
      'vitest/max-nested-describe': ['error', { max: 5 }],
      'vitest/no-alias-methods': 'error',
      'vitest/no-commented-out-tests': 'error',
      'vitest/no-conditional-expect': 'error',
      'vitest/no-conditional-in-test': 'error',
      'vitest/no-conditional-tests': 'error',
      'vitest/no-disabled-tests': 'error',
      'vitest/no-duplicate-hooks': 'error',
      'vitest/no-focused-tests': 'error',
      'vitest/no-hooks': 'off',
      'vitest/no-identical-title': 'error',
      'vitest/no-import-node-test': 'error',
      'vitest/no-interpolation-in-snapshots': 'error',
      'vitest/no-mocks-import': 'error',
      'vitest/no-restricted-matchers': 'off',
      'vitest/no-restricted-vi-methods': 'off',
      'vitest/no-standalone-expect': 'error',
      'vitest/no-test-prefixes': 'off',
      'vitest/no-test-return-statement': 'error',
      'vitest/prefer-called-with': 'error',
      'vitest/prefer-comparison-matcher': 'error',
      'vitest/prefer-each': 'error',
      'vitest/prefer-equality-matcher': 'error',
      'vitest/prefer-expect-assertions': 'error',
      'vitest/prefer-expect-resolves': 'error',
      'vitest/prefer-hooks-in-order': 'error',
      'vitest/prefer-hooks-on-top': 'error',
      'vitest/prefer-lowercase-title': 'error',
      'vitest/prefer-mock-promise-shorthand': 'error',
      'vitest/prefer-snapshot-hint': 'error',
      'vitest/prefer-spy-on': 'error',
      'vitest/prefer-strict-equal': 'error',
      'vitest/prefer-to-be': 'error',
      'vitest/prefer-to-be-falsy': 'error',
      'vitest/prefer-to-be-object': 'error',
      'vitest/prefer-to-be-truthy': 'error',
      'vitest/prefer-to-contain': 'error',
      'vitest/prefer-to-have-length': 'error',
      'vitest/prefer-todo': 'error',
      'vitest/prefer-vi-mocked': 'error',
      'vitest/require-hook': 'error',
      'vitest/require-local-test-context-for-concurrent-snapshots': 'error',
      'vitest/require-to-throw-message': 'error',
      'vitest/require-top-level-describe': 'error',
      'vitest/valid-describe-callback': 'error',
      'vitest/valid-expect': ['error', { alwaysAwait: true }],
      'vitest/valid-expect-in-promise': 'error',
      'vitest/valid-title': 'error',
    },
    settings: {
      vitest: { typecheck: true },
    },
  },
]
